### ISSUE TITLE
Blender Long Start

### ISSUE THREAD

**Issue by Olst88** [samytichadou/Auto_Reload_Blender_addon#20]
Hey 
Thanks for a great addon.
Here is jut minor bug, well, rather specific behavior. When "Check for updates on start" checkbox turned on, if it has bad connection with server, blender start running for a couple minutes.
Bad things that problem is not obvious. So I've spend a lot of time to find the issue turning off and on addons.
After uncheck "Check for updates on start" everything goes well

Probably would be great idea to setup some timout server setting to prevent this behevior.
Regards. Oleg

**Comment by samytichadou** [comment]
thanks for the input, yes i would have to timeout, or doing the check in a different thread to prevent blender from freezing !
I'll take a look into that, thanks !

**Comment by samytichadou** [comment]
no more update check with new version (deprecated with blender extension system), problem solved :)
