### ISSUE TITLE
Auto reload image option does not show on Blender 3.2.2

### ISSUE THREAD

**Issue by pixelartchemist** [samytichadou/Auto_Reload_Blender_addon#21]
![image](https://user-images.githubusercontent.com/60591594/186379888-a6a6b7ab-2a37-47e7-86e8-2562f9a13d26.png)

**Comment by samytichadou** [comment]
Hi, image inspector panel is part of auto reload, check for the topbar header to find the autoreload menu
![image](https://user-images.githubusercontent.com/26276003/187659296-17ae5c4c-4637-4bad-b604-40db5320fe00.png)
