### ISSUE TITLE
"ZIP packaged incorrectly; __init__.py should be in a directory, not at top-level" error when installing on blender 4.1.1

### ISSUE THREAD

**Issue by etherealxx** [samytichadou/Auto_Reload_Blender_addon#31]
is this new addon version for blender 4.2+ only? There's no mention of it on the release note. I just installed it because the addon notifies me for the new version, not knowing the incompatibility.
![image](https://github.com/user-attachments/assets/44df53cd-74fe-491d-87b6-c40f032d4c52)

**Comment by samytichadou** [comment]
yes it is the meaning of "extension format", it is supported by blender 4.2.x only, i'll make that clearer, sorry for the inconvenience

**Comment by samytichadou** [comment]
previous release is still available if needed to work with older blender version
https://github.com/samytichadou/Auto_Reload_Blender_addon/releases/tag/v2_0_3
