### ISSUE TITLE
Image inspector in scene tab missing with new extension version

### ISSUE THREAD

**Issue by loicbramoulle** [samytichadou/Auto_Reload_Blender_addon#32]
this image inspector is missing in the new extension version, I only have it in 4.1 now, and it was reaaally practical:

![image](https://github.com/user-attachments/assets/f322beba-dbdb-48b8-b1e4-ef3ab2167d28)

**Comment by samytichadou** [comment]
Hi thanks for the feedback, new version does not have image manager panel anymore, but you can check this addon : https://github.com/samytichadou/image_manager
it have some specific function for that, not yet an extension though :)

The image manager panel was too messy and poorly coded, and i didn't want to rewrite it in the same addon, makes more sense to have two specific ones, the functions are not the same !

**Comment by loicbramoulle** [comment]
ow I see makes sense, amazing. I initially used auto reload to do crazy stuff with Photoshop real time layer saving to file (file > generate > thingy), but ended up having more essential usecases for the image inspector, that would be a massive handicap not to have anymore, when you need to quickly see which images are missing and where they're supposed to be ect... what images are packed ect.. so strange Blender doesn't have that. Thanks !!!

**Comment by samytichadou** [comment]
You re welcome ! Image manager lacks udim handling for now, but it is on my to do liste to convert it to extension and add it. 
And did you use the old image preview of auto reload ? I was hesitant avout bringing it in (it is not practical to code :) ) and I don't know if this feature is really used or not (I dont use it)
Anyway thanks for feedback and don't hesitate to do feature request on image manager !
