### ISSUE TITLE
about old 3.6 version auto reload releases

### ISSUE THREAD

**Issue by kakitashiya** [samytichadou/Auto_Reload_Blender_addon#33]
i saw the new ver not support old version，but i not found zip file in 2.0.3 assets

**Comment by samytichadou** [comment]
just click on source code on [this page](https://github.com/samytichadou/Auto_Reload_Blender_addon/releases/tag/v2_0_3) and you should be prompted with download of the zip.
The source _was_ the addon before extension version, now i have some extras to "compile" (get rid of extras files and pack in a zip the useful ones), so i put this in the release.
Tell me if it works

**Comment by kakitashiya** [comment]
yes , it work

**Comment by samytichadou** [comment]
Nice ! :) closing the issue
