### ISSUE TITLE
Missing option to add external painting software in the 3.0.3 version // also missing "Donate" and "Check Addon Updates" Buttons

### ISSUE THREAD

**Issue by hrrc** [samytichadou/Auto_Reload_Blender_addon#34]
_Hey,_
so I've come along your addon for Blender through a video from Moltenbolt who did an awesome job showcasing the potential of the AutoReload addon.
After downloading the newest version of the addon (v3.0.3) and installing it on the newest version of Blender (4.2.2) there are some **major UI differences** to the version he used in his video (v2.0.3), which eventually **didn't let me link my external painting software as there is simply no field to link a path or something similar. The "Donate"- and "Check Addon Updates"-Buttons are missing as well.**

It might be the case im overseeing something here, but after some time looking for a solution it occured that im not alone with this issue. For giving a bit more context here is the link to the video im referring to (one of the newest comments on this video):
https://youtu.be/D90UpxA-VDw?si=SqEGV4AWY-yfNDGF&t=215

**And of course I also want to provide you screenshots:**
![Screenshot 2024-10-10 060437 ed](https://github.com/user-attachments/assets/4471860c-1616-404c-9608-7340731cedd0)
![Screenshot 2024-10-10 060954 ed](https://github.com/user-attachments/assets/ccdca117-f87f-4d77-9d32-9586dc8f9d3b)

Quick addition: It seems that binglet0n from the Youtube comment did get it to work with a new blend file from 4.2.2. I however also used a new blend file in 4.2.2 and it didn't show up...

Thank you for making this addon and I hope Im getting to use it properly once I can get behind this issue here👌

**Comment by hrrc** [comment]
Thanks for bringing light into this. And no worries, I think no one can expect a free addon to be on first priority, especially when it's just your hobby. It's your time and I already appreciate you're investing into it + sharing it with others.
Although having images getting reloaded automatically is a nice to have and definitely a time saver.. for me personally the instant reload from the .PSD would've been the biggest time saver as you could literally skip the entire merge->export-process when editing uv maps in 2d while still having a 3d view in Blenders refreshing instantly. So I'd be super excited to see this feature back in the future... ✌️

**Comment by samytichadou** [comment]
Thanks for the kind words, psd auto reload is already in with last version, if not you can report this as a bug :)

**Comment by hrrc** [comment]
uhm, yes i thought since the field for adding the external painting software was missing that wouldn't be a feature lol
Im sorry, it's working now 😃
