### ISSUE TITLE
This thing is hard to find!

### ISSUE THREAD

**Issue by SteveBenz** [samytichadou/Auto_Reload_Blender_addon#4]
The settings for this thing are just as easy to find as any other setting in Blender...  That is to say, it's nigh on impossible for newbs and just plain difficult for everybody else.

Could you post a screenshot or something?  It'd also be nice if you could search for the command to reload, then you could just say "Run search, type 'auto reload'"

Thanks for the Add-on!  It just boggles me that Blender doesn't support this natively.

**Comment by SteveBenz** [comment]
Ugh, are Blender Add-Ons per project or something?  I found that the add-on wasn't activated.  I activated it, and lo, there it was.  Even though I managed to find it, it was several minutes of futzing to do so.  A screenshot would be really good, especially for this case.  If I saw the screenshot and compared it to what I was seeing, I would have guessed that it wasn't installed/activated sooner.  A blurb about the way addons work, if it really does do it per-project, would be super helpful too.

**Comment by cgvirus** [comment]
![Screenshot from 2019-11-18 21-09-00](https://user-images.githubusercontent.com/22106885/69064292-2309f680-0a48-11ea-8333-a7800875d78a.jpg)

**Comment by samytichadou** [comment]
yeah i know, do you have any suggestion for better place for the addon ?

**Comment by SteveBenz** [comment]
Better place?  No, I'm afraid Blender is simply hopeless.  I'd just like the screenshot that @cgvirus posted be put in the ReadMe and whatever place it was that I found the add-on!

**Comment by koloved** [comment]
Better place is to be as part of the TexTools XD

**Comment by SteveBenz** [comment]
I am the newbiest of newbs when it comes to blender.  From this perspective, there is no sensible place in Blender to put it because it's all crazy-town to me.  Even if you found the ideal place in Blender that made sense to experts, it wouldn't do me a bit of good.  Since I don't see an issue like this before, I'm guessing that you have already found a place where people with moderate to high levels of Blender skills can find it.

And yet, newb as I am, I was able to find my way to this addon, and this github page.  What I'd love for you to do is to take the image that @cgvirus posted and stick it in your readme.md.  That's enough.  As far as I'm concerned, you can just delete the video.  There is *so* much going on in that video, so quickly, and the frenetic music doesn't help with that at all.  Videos also take much longer to make than marked-up screenshots, so it's easier to maintain when Blender revs.

**Comment by samytichadou** [comment]
Hey guys, i finally updated the addon !
I reworked the UI and put a bunch of images in the readme to be more clear.
You now have a *Topbar menu* for easy access and some additional features in *Inspector Panels* in the Scene properties !

The Top Bar Menu
![TopBar](https://raw.githubusercontent.com/samytichadou/Auto_Reload_Blender_addon/master/help_images/top_bar_menu_open.png)

Image Inspector Panel
![image_inspector](https://raw.githubusercontent.com/samytichadou/Auto_Reload_Blender_addon/master/help_images/images_inspector_panel.png)

Library Inspector Panel
![library_inspector](https://raw.githubusercontent.com/samytichadou/Auto_Reload_Blender_addon/master/help_images/libraries_inspector_panel.png)

Here's the new release : https://github.com/samytichadou/Auto_Reload_Blender_addon/archive/refs/tags/v2_0_0.zip

**Comment by SteveBenz** [comment]
That looks great!  I've not messed with Blender in a bit, but the new location looks much easier to see and the ReadMe is quite comprehensive!  Thanks!
