### ISSUE TITLE
Annoying Popup

### ISSUE THREAD

**Issue by JamesO2x** [samytichadou/Auto_Reload_Blender_addon#42]
I'm using blender 3.6, and every time I open the program I get an annoying pop up telling me to update this add-on. but when I go to this repository, it tells me that the new update only works in blender 4.2 and later.

Therefore, this annoying nag pop up is entirely pointless. it's telling me to update the add-on, but then the repo says that I can't update the add-on. There should probably be a check somewhere in the update logic that checks which version of blender you are running. If it is lower than 4.2, then don't show the pop up.

I don't want to disable the add-on itself, because it's incredibly useful and I use it everyday. I just wish I could disable the annoying pop up.

**Comment by samytichadou** [comment]
Hi sorry for the inconvenience, you should uncheck "check update on startup" from the addon prefs
Tell me if it solves the problem

**Comment by JamesO2x** [comment]
@samytichadou Wow, I feel dumb. I did not see the checkbox in preferences when I first looked - my eyes must have glossed over it. I'm sorry for the waste of time, haha. The checkbox works, thanks! Great addon!

**Comment by samytichadou** [comment]
> @samytichadou Wow, I feel dumb. I did not see the checkbox in preferences when I first looked - my eyes must have glossed over it. I'm sorry for the waste of time, haha. The checkbox works, thanks! Great addon!

NP, it could definitly be clearer ! Glad you found the addon useful, cheers !
